spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 172.20.60.163
                username: guest
                password: guest
      bindings:
        output:
          destination: test
          binder: rabbit
      rabbit:
        bindings:


